"""
Scores a generated skill document against the required steps in a video task.

Algorithm:
  Component 1 — Step coverage (70%):
    For each required step, check whether any of its keywords appear in the
    lowercased skill document text. No NLP — just substring search.
    coverage_score = steps_covered / total_steps

  Component 2 — Structural completeness (30%):
    Check for the presence of mandatory skill document sections:
      - A # title line
      - A ## Prerequisites section
      - A ## Procedure section
      - At least 3 ### Step headings
      - A ## Expected Output section
    structure_score = sections_present / 5

  Final score = 0.7 * coverage_score + 0.3 * structure_score
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass
class StepResult:
    step_id: str
    step_key: str
    category: str
    covered: bool
    matched_keyword: str | None


@dataclass
class VideoScoreResult:
    score: float                             # 0.0 – 1.0 weighted composite
    coverage_score: float                    # keyword coverage (0.0 – 1.0)
    structure_score: float                   # structural completeness (0.0 – 1.0)
    covered: list[StepResult] = field(default_factory=list)
    missed: list[StepResult] = field(default_factory=list)
    structure_checks: dict[str, bool] = field(default_factory=dict)

    @property
    def n_steps(self) -> int:
        return len(self.covered) + len(self.missed)

    @property
    def n_covered(self) -> int:
        return len(self.covered)

    def by_category(self) -> dict[str, dict]:
        cats: dict[str, dict[str, int]] = {}
        for r in self.covered + self.missed:
            c = cats.setdefault(r.category, {"covered": 0, "total": 0})
            c["total"] += 1
            if r.covered:
                c["covered"] += 1
        return {
            cat: {
                "covered": v["covered"],
                "total": v["total"],
                "rate": v["covered"] / v["total"],
            }
            for cat, v in cats.items()
        }


def _normalise(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower())


_STRUCTURE_PATTERNS: dict[str, re.Pattern] = {
    "has_title":          re.compile(r"^#\s+\S", re.MULTILINE),
    "has_prerequisites":  re.compile(r"##\s+Prerequisites", re.IGNORECASE),
    "has_procedure":      re.compile(r"##\s+Procedure", re.IGNORECASE),
    "has_numbered_steps": re.compile(r"###\s+Step\s+\d", re.IGNORECASE),
    "has_expected_output": re.compile(r"##\s+Expected\s+Output", re.IGNORECASE),
}

_MIN_NUMBERED_STEPS = 3


def _check_structure(skill_doc: str) -> dict[str, bool]:
    checks: dict[str, bool] = {}
    for name, pattern in _STRUCTURE_PATTERNS.items():
        if name == "has_numbered_steps":
            checks[name] = len(pattern.findall(skill_doc)) >= _MIN_NUMBERED_STEPS
        else:
            checks[name] = bool(pattern.search(skill_doc))
    return checks


def score_skill_doc(skill_doc: str, task: dict) -> VideoScoreResult:
    """
    Args:
        skill_doc: The skill document generated by the agent (free-form markdown).
        task:      A task dict from video_tasks.json, containing 'required_steps'.

    Returns:
        VideoScoreResult with composite score, per-step detail, and structure checks.
    """
    norm = _normalise(skill_doc)
    step_results: list[StepResult] = []

    for step in task["required_steps"]:
        matched: str | None = None
        for keyword in step["keywords"]:
            if _normalise(keyword) in norm:
                matched = keyword
                break

        step_results.append(StepResult(
            step_id=step["id"],
            step_key=step["step_key"],
            category=step["category"],
            covered=matched is not None,
            matched_keyword=matched,
        ))

    covered = [r for r in step_results if r.covered]
    missed = [r for r in step_results if not r.covered]
    coverage_score = len(covered) / len(step_results) if step_results else 0.0

    structure_checks = _check_structure(skill_doc)
    structure_score = sum(structure_checks.values()) / len(structure_checks)

    score = round(0.7 * coverage_score + 0.3 * structure_score, 4)

    return VideoScoreResult(
        score=score,
        coverage_score=round(coverage_score, 4),
        structure_score=round(structure_score, 4),
        covered=covered,
        missed=missed,
        structure_checks=structure_checks,
    )


def aggregate(results: list[VideoScoreResult]) -> dict:
    """Summarise a batch of VideoScoreResults for epoch-level reporting."""
    if not results:
        return {}
    scores = [r.score for r in results]
    coverage_scores = [r.coverage_score for r in results]
    structure_scores = [r.structure_score for r in results]
    total_steps = sum(r.n_steps for r in results)
    total_covered = sum(r.n_covered for r in results)

    cat_totals: dict[str, dict[str, int]] = {}
    for result in results:
        for cat, data in result.by_category().items():
            acc = cat_totals.setdefault(cat, {"covered": 0, "total": 0})
            acc["covered"] += data["covered"]
            acc["total"] += data["total"]

    return {
        "mean_score":           sum(scores) / len(scores),
        "min_score":            min(scores),
        "max_score":            max(scores),
        "mean_coverage_score":  sum(coverage_scores) / len(coverage_scores),
        "mean_structure_score": sum(structure_scores) / len(structure_scores),
        "total_steps":          total_steps,
        "total_covered":        total_covered,
        "overall_coverage_rate": total_covered / total_steps if total_steps else 0.0,
        "by_category": {
            cat: {**v, "rate": v["covered"] / v["total"]}
            for cat, v in cat_totals.items()
        },
    }
